//============================================================================
//  asc - Enhanced Apple Sound Chip (Quadra 900/950)
//
//  Models the ASC in FIFO mode - the path classic Mac sound uses: two 1 KB
//  byte FIFOs (channel A = left, B = right) that the CPU fills with 8-bit
//  offset-binary samples (0x80 = silence), played out at ~22.257 kHz. Samples
//  are converted to signed 16-bit for the MiSTer audio path:
//        s16 = (sample8 - 128) << 8.
//  A half-empty interrupt is raised so the driver can refill.
//
//  Playback is paced by snd_ce (one pulse per output sample), generated by the
//  top level from the system clock. Verified in sim/iverilog/tb_asc.v.
//
//  Simplified: no 4-voice wavetable mode, no DFAC record path, single fixed
//  rate. Register layout is a clean local map, not the exact ASC addresses
//  (documented TODO; validate against a real ROM/driver).
//
//  Local map (offset within the ASC space):
//    0x001         mode      (bit0 = FIFO enable)
//    0x00B (read)  status    ({a_empty,b_empty, a_half,b_half})
//    0x800-0xBFF   FIFO A (left)  push on write
//    0xC00-0xFFF   FIFO B (right) push on write
//============================================================================

module asc
(
	input             clk,
	input             reset,
	input             snd_ce,      // one pulse per output sample (~22.257 kHz)

	// CPU register / FIFO access
	input             sel,
	input      [11:0] addr,
	input      [7:0]  din,
	output reg [7:0]  dout,
	input             rw,          // 1 = read
	output reg        ack,
	output            irq,

	// 16-bit signed stereo to the framework
	output reg signed [15:0] audio_l,
	output reg signed [15:0] audio_r
);

	reg [7:0] fifoA [0:1023];
	reg [7:0] fifoB [0:1023];
	reg [10:0] a_wr, a_rd, b_wr, b_rd;   // 11-bit so wr-rd gives a true level
	reg        mode_en;

	wire [10:0] a_level = a_wr - a_rd;
	wire [10:0] b_level = b_wr - b_rd;
	wire a_empty = (a_level == 0);
	wire b_empty = (b_level == 0);
	wire a_half  = (a_level < 11'd512);
	wire b_half  = (b_level < 11'd512);

	// half-empty interrupt while enabled
	assign irq = mode_en & (a_half | b_half);

	// One transfer per bus cycle: act only on the first cycle sel is high
	// (before ack), so a multi-cycle sel assertion pushes a sample only once.
	wire acc    = sel & ~ack;
	wire push_a = acc & ~rw & (addr[11:10] == 2'b10);
	wire push_b = acc & ~rw & (addr[11:10] == 2'b11);
	wire reg_wr = acc & ~rw & (addr[11] == 1'b0);

	function signed [15:0] to_s16(input [7:0] s);
		to_s16 = $signed({s, 8'b0}) - 16'sd32768;   // (s-128)<<8
	endfunction

	always @(posedge clk) begin
		if (reset) begin
			a_wr <= 0; a_rd <= 0; b_wr <= 0; b_rd <= 0;
			mode_en <= 0; audio_l <= 0; audio_r <= 0; ack <= 0; dout <= 0;
		end else begin
			ack <= 1'b0;

			// ---- CPU access ----
			if (push_a) begin fifoA[a_wr[9:0]] <= din; a_wr <= a_wr + 1'b1; end
			if (push_b) begin fifoB[b_wr[9:0]] <= din; b_wr <= b_wr + 1'b1; end
			if (reg_wr && addr[3:0] == 4'h1) mode_en <= din[0];

			if (sel & rw) begin
				case (addr[3:0])
					4'h1:    dout <= {7'd0, mode_en};
					4'hB:    dout <= {a_empty, b_empty, a_half, b_half, 4'd0};
					default: dout <= 8'h00;
				endcase
			end
			if (sel && !ack) ack <= 1'b1;

			// ---- playback ----
			if (snd_ce) begin
				if (mode_en && !a_empty) begin
					audio_l <= to_s16(fifoA[a_rd[9:0]]);
					a_rd <= a_rd + 1'b1;
				end else if (!mode_en) audio_l <= 16'sd0;
				// (FIFO empty: hold last sample)

				if (mode_en && !b_empty) begin
					audio_r <= to_s16(fifoB[b_rd[9:0]]);
					b_rd <= b_rd + 1'b1;
				end else if (!mode_en) audio_r <= 16'sd0;
			end
		end
	end

endmodule
